pull_request_rules:
  - name: Automatic PR merging for DiAGRAM
    conditions:
      - "author=dependabot[bot]"
      - "check-success=Wiz Data Scanner"
      - "check-success=Wiz IaC Scanner"
      - "check-success=Wiz Secret Scanner"
      - "check-success=Wiz Vulnerability Scanner"
    actions:
      review:
        type: APPROVE
        message: Automatically approving and merging DiAGRAM PRs
      queue:
        name: default
