queue_rules:
  - name: default
    conditions:
      - "check-success=Wiz Data Scanner"
      - "check-success=Wiz IaC Scanner"
      - "check-success=Wiz Secret Scanner"
      - "check-success=Wiz Vulnerability Scanner"
pull_request_rules:
  - name: automatic merge for Scala Steward
    conditions:
      - "check-success=Wiz Data Scanner"
      - "check-success=Wiz IaC Scanner"
      - "check-success=Wiz Secret Scanner"
      - "check-success=Wiz Vulnerability Scanner"
    actions:
      review:
        type: APPROVE
        message: Automatically approving DiAGRAM PR
      queue:
        name: default
