---
title: "Directory Structure"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Directory Structure}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This document aims to serve as an overview of all of the assets in the package.

## DESCRIPTION

Top level packages description, it's primary function is to lay out the dependencies for our application, all of the packages that are required to run the application should be listed here.

## NAMESPACE

Should not need to be edited manually, describes the functions and classes that are imported from other packages for use in our application and the exports of our package.

## R

This directory contains the bulk of the R source code that make up the application. 

## docs

This directory was auto generated by `pkgdown` for providing a nice user friendly website interface to browsing package documentation.

## man

This directory is created as part of the package build process, the files are created by parsing the documentation strings found within the R source code. 

## srcjs

This directory contains JavaScript source code for some of the custom widgets functionality in the application. In particular the sliders, both the triple linked slider and the single slider with linked text input are defined here. This code is React JSX, which gets transpiled into JavaScript as part of the build process, documented in the overview document, using the `package.json` and `webpack.config.js` files.

## inst 

This directory contains all other non R code assets and is broken up into many subdirectories

### inst/www

This is created as part of the build process for the transpiled JSX from the `srcjs` directory, there is no manually edited code here, and nothing here that you should need to edit directly.

### inst/text_content

The markdown source for a large amount of the text content is here. For example the text content that appears on the home page, guidance, learn about, glossary tabs among others in fairly intuitive named files. Almost all large bodies of text that you expressed interest in having the ability to edit, are here. 

* `report_summary.md` - The text that appears at the top of the report tab
* `learn_about.md` - The text that appears on the Learn about DiAGRAM tab (previsouly called definitions)
* `home_content.md` - The text that appears on the home tab
* `guidance.md` and `guidance_extra.md` - The text that appears on the guidance tab or "How to use the tool". It is split in two to reflect the two parts of the guidance tab.
* `glossary.md` - The glossary text.
* `footer.md` - The content of the footer across the application
* `final_question.yml` - A yaml file that lays out the structure of the questions for creating models and scenarios
* `DiAGRAM-Roboto.svg` - Your logo, such that it is visible to the rendering process for the markdown text files contained here. 
* `final_questions.Rmd` - Source rmarkdown file to be able to recreate the downloadable set of questions.
* `final_questions.pdf` - A pre-rendered copy of the questions for download from the application.

I believe that the other files here are no longer needed, they are either legacy from your original application or were created as we iterated on ideas through the sprints and were not yet removed. As part of my tidying up I am trying to ensure they can safely be removed and removing them.

### inst/scripting

This was a location I made for the purpose of being able to quickly test things out without having to change things within the application such that I could check they worked without risking breaking things as we approached user testing sessions. It should be safe to delete them as they application itself should not rely on them. I am ensuring as part of my tidy up that they can safely be deleted.

### inst/rmarkdown

Formal definition for a rmarkdown template for your downloadable pdf assets. Also discussed in the overview documentation. I think the only files you might want to change are in 

```
inst/rmarkdown/templates/nata-report/resources
```

* `template.tex` - Defines the structure of the pdf reports, including font and colour definitions of the pdfs.
* `tna-logo.png` - The logo used for the front page of the pdf reports.
* `*.otf` and `*.ttf` are font definition files. If you want to change to other custom fonts, you will likely have to include the respective font files here, and update the template.tex file to register the font. The template includes examples of doing this in line with the fonts that you have as part of the report.

Incidentally, the pdf template here is not restricted to use within this application. If you like the style and have other reports that you generate using R code for graphics or analysis this template is reusable. Installing the package `diagramNAT` will also enter the necessary information for the RStudio IDE such that if you want to create a report in this style, you can go

```
File -> New File -> Rmarkdown 
```

Select "From template" in the pop up menu and then choose "NATA report" to get a skeleton Rmarkdown document. 

### inst/example

This contains an example of the runnable application. This code could be used to run the app using the questions and default responses stored within the package. It also serves as an example for a deployable app script.

### inst/default_model

This directory contains the stored bayesian network `.bif` file that you gave us at project inception, which is used throughout the application as well as various versions of default data that we tried in the application.

* `new.json` - The new style questions default data (i.e those with multiple parts included) This is the version that is actually deployed and was used in the final user test sessions.
* `default_response.json` - The original 9 questions set of responses. Essentially the first version we had. 
* `commercial_backup.json` - The commercial back up that we had put together ready when the original 9 questions were in place. 

I think all files except `new.json` and `Model.bif` can be safely removed, but am checking this as part of my tidy up.

### inst/assets

This is the directory that houses all the other custom assets for the web application, including styling information, other small pieces of custom JavaScript logic etc.

#### inst/assets/www

This directory is public to the web application allowing users to be able to access them from their browser. As such no private files or information should ever be stored here. The directory contains all the logo images included within the application. A copy of the final downloadable question pdf and your logo such that they are accessible to the front facing web page. The general styling rules for the application are also defined here across a series of `.css` files.

The `.css` files is where the majority of colour, padding and other purely visual settings are made such that they are consistent across all tabs in the application. Things like your buttons colours, text box colours, menu and general theming are stored in these files.

#### inst/assets/templates

This directory contains the two templates used to render the downloadble reports with their data on the fly by the application. Each model together with it's associated scenarios is put through the `pdf_section.Rmd` and all sections are put together by the `pdf_template.Rmd`.

#### inst/assets/js

Small JavaScript utilities, such as the functionality for popups, the warning of closing the tab are in this directory.

## tests

A directory for writing unit tests for R code logic. This is where some initial tests were located and if we had more time where we would add additional tests for R code logic.
