---
params:
  req: NA # request object for a single model
---

```{r include = FALSE}
library(magrittr)
req = params$req
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
question_data = diagramLambda::get_questions_tibble()
base_model = diagramLambda::get_base_model(req)
policies = diagramLambda::find_scenario_diffs(req)
comments_data = diagramLambda::get_comments(req)
scenario_names = diagramLambda::get_scenario_names(req)

model_name = base_model$model_name
```

## Model: `r model_name`

```{r plot-chunk}
print_plot = function(model_name) {
  p = bar_chart(model_name)
  print(p)
}

print_plot(req)
```

### Comments

```{r comment-chunk, results='asis'}
no_comments_flag = sum(nchar(comments_data)) == 0
cat("\n\n")
if (no_comments_flag) {
  cat("There were no comments attached to this model.")
} else {
  purrr::walk2(
    scenario_names, comments_data, ~{
      cat(glue::glue("* **{.x}:** - {.y}"), "\n")
    }
  )
}
cat("\n\n")
```


### Responses to Questions

```{r response-chunk, results='asis'}
any_policies = length(policies) > 0
cat(glue::glue(
  "Here is a summary of the responses given for the model{if(any_policies) ' and each scenario.' else '.'}" # nolint
))
```

```{r, results = 'asis'}
cat("\n\n### Baseline Model\n\n")
```
```{r advanded-chunk, results='asis'}
is_advanced = !is.null(base_model$data$advanced)
if (is_advanced) {
  cat("**This is an advanced model**\n\n")
  simple_base = base_model
  class(simple_base) = c("simple_responses", "list")
  purrr::iwalk(base_model$data$advanced, ~{
    name = .node_map[.y]
    cat(glue::glue("\n\n#### {name}\n\n"))
    colnames(.x) = colnames(.x) %>%
      stringr::str_replace_all("_", " ") %>%
      stringr::str_to_title()
    knitr::kable(.x, format = "latex", longtable = TRUE, booktabs = TRUE) %>%
    kableExtra::kable_styling(font_size = 7, full_width = TRUE, latex_options = c("repeat_header")) %>%
    cat()
  cat("\n\n")
  })
  # diagramLambda::join_questions_responses(question_data, simple_base)
} else {
  diagramLambda::join_questions_responses(question_data, base_model) %>%
    diagramLambda::pdf_table() %>%
    knitr::kable(format = "latex", longtable = TRUE, booktabs = TRUE) %>%
    kableExtra::kable_styling(font_size = 7, full_width = TRUE, latex_options = c("repeat_header")) %>%
    cat()
  cat("\n\n")
}

```

```{r policy-chunk, results='asis'}
if (any_policies) {
  purrr::walk(policies, function(x) {
    y = x$name
    if (nrow(x$data) > 0) {
      cat("### ", y, "\n\n")
      cat(glue::glue("The following responses were changed for {y}."), "\n\n")
      diagramLambda::join_questions_responses(question_data, x) %>%
        diagramLambda::diff_table() %>%
        knitr::kable(format = "latex", longtable = TRUE, booktabs = TRUE) %>%
        kableExtra::kable_styling(font_size = 7, full_width = TRUE, latex_options = c("repeat_header")) %>%
        cat()
      cat("\n\n")
    }
  })
}
```
