---
params:
  model_name: NA
  vis_data: NA
  download_data: NA
  question_data: NA
---

```{r include = FALSE}
question_data = params$question_data
download_data = params$download_data
vis_data = params$vis_data
model_name = params$model_name
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

## Model: `r model_name`

```{r}
print_plot = function(model_name) {
  df = vis_data %>% dplyr::filter(.data$Model == model_name)
  annotations = df %>%
    dplyr::select(.data$Model, .data$Policy, .data$`Intellectual Control`, .data$Renderability) %>%
    tidyr::pivot_longer(c("Intellectual Control", "Renderability"), names_to = "Metric", values_to = "Score") %>%
    dplyr::mutate(
      Policy = tidyr::replace_na(.data$Policy, "baseline"),
      Score = round(.data$Score * 100),
    ) 
  p = policy_bar_gg(df)
  p = p + ggplot2::geom_text(
    data = annotations, 
    ggplot2::aes(
      x = .data$Policy, 
      y = pmax(.data$Score -2, 1), 
      label = .data$Score, 
      group = .data$Metric
    ), 
    position = ggplot2::position_dodge2(width = .9, preserve = "single")
  ) + ggplot2::theme(
    strip.background = ggplot2::element_blank(),
    strip.text.x = ggplot2::element_blank()
  )
  print(p)
}

print_plot(model_name)
```

## Responses to Questions

Here is a summary of the responses given for the model and each scenario.
```{r, results='asis'}
any_policies = length(setdiff(download_data$Policy, "baseline")) > 0
cat(glue::glue("Here is a summary of the responses given for the model{if(any_policies) ' and each scenario.' else '.'}"))
```

### Baseline Model

```{r, results='asis'}
policy_diff = find_diff(download_data, model_name)

download_data %>% 
  dplyr::filter(.data$Model == model_name) %>%
  dplyr::select(.data$Question, .data$Detail, .data$Response) %>%
  dplyr::mutate(
    Question = ifelse(c(FALSE, .data$Question[2:dplyr::n()] == .data$Question[1:(dplyr::n() - 1)]), '', .data$Question),
    Detail = tidyr::replace_na(.data$Detail, ''),
    Question = tidyr::replace_na(.data$Question, '')
  ) %>%
  knitr::kable(format = "latex", longtable = TRUE, booktabs = TRUE) %>% 
  kableExtra::kable_styling(full_width = TRUE, font_size = 7) %>%
  cat()
```

```{r, results='asis'}
purrr::iwalk(policy_diff, function(x, y) {
  cat("### ", y, "\n\n")
  cat(glue::glue("The following responses were changed for {y}."), "\n\n")
  x %>% 
    dplyr::filter(.data$Model == model_name) %>%
    dplyr::select(.data$Question, .data$Detail, .data$Response) %>%
  dplyr::mutate(
    Question = ifelse(c(FALSE, .data$Question[2:dplyr::n()] == .data$Question[1:(dplyr::n() - 1)]), '', .data$Question),
    Detail = tidyr::replace_na(.data$Detail, '')
  ) %>%
    knitr::kable(format = "latex", longtable = TRUE, booktabs = TRUE) %>%
    kableExtra::kable_styling(full_width = TRUE, font_size = 7) %>%
    cat()
  
})
```

