devtools::load_all()
questions = diagramNAT::read_config(system.file("text_content", "final_questions.yml", package = "diagramNAT"))
default_response = diagramNAT::load_single_response(system.file("default_model", "new.json", package = "diagramNAT"))
model = bnlearn::read.bif(system.file("default_model", "Model.bif", package = "diagramNAT"))
diagramNAT::run_app(questions, default_response, model)
#options(markdown.extensions = c(getOption("markdown.extensions"), "fenced_divs"))
