name: Deploy DiAGRAM
permissions:
  id-token: write
  contents: write
on:
  push:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment'
        required: true
        options:
          - intg
          - prod
        default: 'intg'
      to-deploy:
        description: 'Version to deploy'
        required: true
run-name: Deploying DiAGRAM ${{inputs.to-deploy}} to ${{inputs.environment}}
jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials for ECR
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_NUMBER }}:role/Role_Diagram_GitHub_OICD
          aws-region: eu-west-2
          role-session-name: ECRLogin
      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.MANAGEMENT_ACCOUNT }}.dkr.ecr.eu-west-2.amazonaws.com
      - name: Tag image
        run: |
          docker pull ${{ secrets.MANAGEMENT_ACCOUNT }}.dkr.ecr.eu-west-2.amazonaws.com/diagram-backend-lambda-runtimes:${{ github.event.inputs.to-deploy }}
          docker tag ${{ secrets.MANAGEMENT_ACCOUNT }}.dkr.ecr.eu-west-2.amazonaws.com/diagram-backend-lambda-runtimes:${{ github.event.inputs.to-deploy }} ${{ secrets.MANAGEMENT_ACCOUNT }}.dkr.ecr.eu-west-2.amazonaws.com/diagram-backend-lambda-runtimes:${{ github.event.inputs.environment }}
          docker push ${{ secrets.MANAGEMENT_ACCOUNT }}.dkr.ecr.eu-west-2.amazonaws.com/diagram-backend-lambda-runtimes:${{ github.event.inputs.environment }}
          git branch -f release-${{ github.event.inputs.environment }} HEAD
          git push -f origin release-${{ github.event.inputs.environment }}
          git tag ${{ steps.next-tag.outputs.next-version }}
          git push origin ${{ steps.next-tag.outputs.next-version }}
        env:
          MANAGEMENT_ACCOUNT_NUMBER: ${{ secrets.MANAGEMENT_ACCOUNT }}
          DOCKER_TAG: ${{ github.event.inputs.to-deploy }}
          ENVIRONMENT_TAG: ${{ github.event.inputs.environment }}
      - name: Send success message
        uses: nationalarchives/tdr-github-actions/.github/actions/slack-send@main
        with:
          message: "*DiAGRAM* :whale: The '${{ github.event.inputs.to-deploy }}' image has been tagged with '${{ github.event.inputs.environment }}' in ECR"
          slack-url: ${{ secrets.SLACK_WEBHOOK }}
      - name: Send failure message
        uses: nationalarchives/dr2-github-actions/.github/actions/slack-send@main
        if: failure()
        with:
          message: ":warning: Build failed for DiAGRAM <https://github.com/nationalarchives/DiAGRAM/actions/runs/${{ github.run_id }}|View the failed workflow>"
          slack-url: ${{ secrets.SLACK_WEBHOOK }}