name: DiAGRAM release to live
on:
  workflow_dispatch:
permissions:
  id-token: write
run-name: DiAGRAM e2e Tests - dev
jobs:
  deploy-to-live:
    runs-on: ubuntu-latest
    environment: live
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          repository: 'nationalarchives/DiAGRAM-terraform'
          path: terraform
      - uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 #v6.0.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_NUMBER }}:role/DiagramTerraformRole
          aws-region: eu-west-2
          role-session-name: TerraformRole
      - name: Deploy Lambda function with container image
        uses: aws-actions/aws-lambda-deploy@29ea35c124579506cf0475e20df36198eb670d89 #v1.1.0
        with:
          function-name: diagram-backend
          package-type: Image
          image-uri: ${{ secrets.MANAGEMENT_ACCOUNT }}.dkr.ecr.eu-west-2.amazonaws.com/diagram-backend-lambda-runtimes:live
