name: DiAGRAM e2e Tests
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment to run tests against'
        required: true
        options:
          - dev
          - live
        default: 'dev'

run-name: DiAGRAM e2e Tests - ${{ github.event.inputs.environment }}
jobs:
  cypress-e2e:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: npm --prefix tests cit
