name: DiAGRAM e2e Tests
on:
  push:
    branches:
      - DR2-2220-Write-DiAGRAM-tests
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment'
        required: true
        options:
          - dev
          - live
        default: 'dev'

run-name: DiAGRAM e2e Tests - ${{ github.event.inputs.environment }}
jobs:
  cypress-e2e:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: npm --prefix tests cit

      - name: Send success message
        uses: nationalarchives/dr2-github-actions/.github/actions/slack-send@main
        with:
          message: "*DiAGRAM* The e2e tests for environment: '${{ github.event.inputs.environment }}' finished successfully"
          slack-url: ${{ secrets.SLACK_WEBHOOK }}

      - name: Send failure message
        uses: nationalarchives/dr2-github-actions/.github/actions/slack-send@main
        if: failure()
        with:
          message: ":warning: e2e tests failed for DiAGRAM for environment: '${{ github.event.inputs.environment }}'"
          slack-url: ${{ secrets.SLACK_WEBHOOK }}