name: DiAGRAM Tests
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment to run the tests in'
        required: true
        options:
          - live
          - dev
          - DR2-2220-Write-DiAGRAM-tests
        default: 'DR2-2220-Write-DiAGRAM-tests'

run-name: Running DiAGRAM tests for ${{ github.event.inputs.environment }} environment
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: npm --prefix tests cit
      - name: Send success message
        uses: nationalarchives/dr2-github-actions/.github/actions/slack-send@main
        with:
          message: "DiAGRAM tests have been run successfully in the ${{ github.event.inputs.environment }} environment."
          slack-url: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: send failure message
        uses: nationalarchives/dr2-github-actions/.github/actions/slack-send@main
        if: failure()
        with:
          message: "DiAGRAM tests have failed in the ${{ github.event.inputs.environment }} environment."
          slack-url: ${{ secrets.SLACK_WEBHOOK_URL }}
