name: Update frontend application

on:
  push:
    paths:
      - app/**
      - .github/workflow/update-frontend.yml
    branches:
      - live
      - stage
      - dev

jobs:

  update_site_env_matching_branch:
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"

    steps:

      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install node dependencies
        working-directory: ./app
        run: npm ci

      - name: Build static site 
        working-directory: ./app
        run: npm run build

      - name: Update static site hosted in S3
        run: aws s3 sync ./app/dist s3://${{ secrets.BUCKET_NAME }}/ --delete
