name: Update frontend

on:
  push:
    branches:
      - live
    paths:
      - app/**
      - .github/workflow/update-frontend.yml
jobs:
  update_site_env_matching_branch:
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
      - name: run-release-process
        run:
          gh workflow run release.yml
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
